version: '3.9'
services:
  indextrackerassessmentaj:
    image: indextrackerassessmentaj
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    volumes:
    #  - ../:/app
      - ../backend-service:/app/backend-service
      - type: bind
        source: ../backend-service/app/index.db
        target: /app/backend-service/app/index.db
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_PATH=app/index.db
    networks:
      - backend-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge